# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-12 09:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gamecore_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='id',
        ),
        migrations.AddField(
            model_name='player',
            name='nickname',
            field=models.CharField(default='0000000', max_length=120, primary_key=True, serialize=False, verbose_name='Gamecore User Name'),
        ),
        migrations.AlterField(
            model_name='player',
            name='company',
            field=models.CharField(max_length=120, verbose_name='Company Name'),
        ),
        migrations.AlterField(
            model_name='player',
            name='email',
            field=models.CharField(max_length=120, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='player',
            name='first_name',
            field=models.CharField(max_length=120, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='player',
            name='flag_pc',
            field=models.BooleanField(default=False, verbose_name='Do you play in PC?'),
        ),
        migrations.AlterField(
            model_name='player',
            name='flag_playstation',
            field=models.BooleanField(default=False, verbose_name='Do you play in Playstation?'),
        ),
        migrations.AlterField(
            model_name='player',
            name='flag_xbox',
            field=models.BooleanField(default=False, verbose_name='Do you play in Xbox?'),
        ),
        migrations.AlterField(
            model_name='player',
            name='last_name',
            field=models.CharField(max_length=120, verbose_name='Second Name'),
        ),
        migrations.AlterField(
            model_name='player',
            name='password_first',
            field=models.CharField(max_length=120, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='player',
            name='password_second',
            field=models.CharField(max_length=120, verbose_name='Password (repeat for validation)'),
        ),
    ]
