# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-13 03:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gamecore_app', '0003_auto_20161213_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='message',
            field=models.CharField(max_length=1200, verbose_name='Message'),
        ),
    ]
