# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-13 03:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gamecore_app', '0004_auto_20161213_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='welcoming_message',
            field=models.CharField(default='', max_length=1200),
        ),
    ]
