# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-13 10:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gamecore_app', '0005_player_welcoming_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogIn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(default='', max_length=120)),
                ('password', models.CharField(default='', max_length=120)),
                ('loginTime', models.DateField()),
            ],
        ),
    ]
