# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-20 08:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gamecore_app', '0007_auto_20161219_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='timeDate',
            field=models.CharField(max_length=120, verbose_name='Match date'),
        ),
    ]
