# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-20 08:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Gamecore_app', '0008_auto_20161220_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='player2',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='player2', to='Gamecore_app.Player'),
        ),
        migrations.AlterField(
            model_name='match',
            name='player1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player1', to='Gamecore_app.Player'),
        ),
    ]
