# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-20 16:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Gamecore_app', '0009_auto_20161220_0945'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerAvailability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available', models.CharField(max_length=300, verbose_name='Update your availability for the next days/weeks')),
                ('player_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gamecore_app.Player')),
            ],
        ),
    ]
