# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-22 10:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gamecore_app', '0010_playeravailability'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='available',
            field=models.CharField(default='', max_length=300, verbose_name='Update your availability for the next days/weeks'),
        ),
    ]
