# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-22 10:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gamecore_app', '0011_player_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playeravailability',
            name='player_id',
        ),
        migrations.DeleteModel(
            name='PlayerAvailability',
        ),
    ]
