# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-22 16:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gamecore_app', '0012_auto_20161222_1136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ladder',
            name='player_id',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='Result',
            new_name='Score',
        ),
        migrations.DeleteModel(
            name='Ladder',
        ),
    ]
