# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-22 16:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Gamecore_app', '0013_auto_20161222_1742'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ladder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gamecore_app.Match')),
                ('player_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gamecore_app.Player')),
            ],
        ),
    ]
