# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-22 18:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gamecore_app', '0016_auto_20161222_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ladder',
            name='possesion',
            field=models.FloatField(default=0.0, null=True, verbose_name='posession'),
        ),
    ]
