# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-22 18:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gamecore_app', '0017_auto_20161222_1900'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ladder',
            old_name='possesion',
            new_name='posession',
        ),
    ]
