# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-23 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gamecore_app', '0018_auto_20161222_1902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ladder',
            name='posession',
        ),
        migrations.AddField(
            model_name='ladder',
            name='possession',
            field=models.FloatField(default=0.0, null=True, verbose_name='possession'),
        ),
    ]
