# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-24 13:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Gamecore_app', '0019_auto_20161223_1252'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuggestedLeague',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.CharField(default='', max_length=120)),
                ('platform', models.CharField(default='', max_length=120)),
                ('time', models.DateField()),
                ('user_nickname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gamecore_app.Player')),
            ],
        ),
    ]
