# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-24 23:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gamecore_app', '0020_suggestedleague'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='loginTime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='suggestedleague',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
