# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-24 23:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gamecore_app', '0021_auto_20161225_0023'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
