# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-25 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gamecore_app', '0022_contactus_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='playstation_id',
            field=models.CharField(default='', max_length=120, verbose_name='PlayStation ID'),
        ),
        migrations.AlterField(
            model_name='player',
            name='flag_pc',
            field=models.BooleanField(default=False, verbose_name='Do you play in PC?  '),
        ),
        migrations.AlterField(
            model_name='player',
            name='flag_playstation',
            field=models.BooleanField(default=False, verbose_name='Do you play in Playstation?  '),
        ),
        migrations.AlterField(
            model_name='player',
            name='flag_xbox',
            field=models.BooleanField(default=False, verbose_name='Do you play in Xbox?  '),
        ),
        migrations.AlterField(
            model_name='player',
            name='password_second',
            field=models.CharField(max_length=120, verbose_name='Password confirmation'),
        ),
    ]
