# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-25 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gamecore_app', '0024_auto_20161225_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='available',
            field=models.CharField(default='', max_length=300, verbose_name='Update your availability for the next days/weeks'),
        ),
        migrations.AlterField(
            model_name='player',
            name='welcoming_message',
            field=models.CharField(default='Welcome to the game! Tell us your availability and your networking interests and we will set up the right games for you!', max_length=1200),
        ),
    ]
